env:
  browser: true
  es6: true
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    jsx: true
extends:
  - eslint:recommended
  - plugin:prettier/recommended
plugins:
  - react
globals:
  document: false
  console: false
rules:
  sourceType: module
  no-console: "off" 
  no-unused-vars:
    - "error"
    - varsIgnorePattern: "^h$|^_\\w*"
      argsIgnorePattern: "^h$|^_\\w*"
# rules for prettier
  prettier/prettier:
    - "error"
    - singleQuote: false
      trailingComma: es5
      semi: false
# rules for jsx
  react/jsx-boolean-value: "error"
  react/jsx-closing-bracket-location: "error"
  react/jsx-closing-tag-location: "error"
  react/jsx-curly-spacing: "error"
  react/jsx-equals-spacing: "error"
  react/jsx-indent: ["error", 2]
  react/jsx-props-no-multi-spaces: "error"
  react/jsx-tag-spacing:
    - "error"
    - beforeClosing: "never"
  react/jsx-uses-vars: "error"
  react/jsx-wrap-multilines: "error"